/**
 * NIS2 scope-check Telegram bot — Cloudflare Pages Function (webhook).
 *
 * STATELESS + DETERMINISTIC (zero LLM, zero database):
 *   - the 2-question decision tree is encoded in inline-button callback_data
 *   - the email step uses force_reply; the market+score are recovered from the
 *     prompt text (reply_to_message), so no KV/session store is needed
 *   - lead capture forwards to that market's own /subscribe endpoint, so the
 *     existing per-market beehiiv + Resend nurture sequence fires automatically
 *
 * Generated by tools/telegram_bot/build_bot.py — DO NOT edit by hand.
 * Env vars (Cloudflare Pages -> Settings -> Environment variables):
 *   TELEGRAM_BOT_TOKEN   (required)  — the bot token
 *   TG_WEBHOOK_SECRET    (optional)  — if set, must match the setWebhook secret_token
 */
const CONFIG = {
  "botUser": "nis2network_bot",
  "markets": {
    "pl": {
      "country": "Polska",
      "lang": "pl",
      "domain": "nis2-narzedzia.pl",
      "subscribe": "https://nis2-narzedzia.pl/subscribe",
      "links": [
        {
          "text": "Porównanie narzędzi NIS2",
          "url": "https://nis2-narzedzia.pl/porownanie"
        },
        {
          "text": "Kalkulator kosztów NIS2",
          "url": "https://nis2-narzedzia.pl/kalkulator-kosztow-nis2"
        }
      ],
      "strings": {
        "greeting": "Cześć. Ten bot to bezpłatny, dwupytaniowy test wstępny: czy Twoja organizacja prawdopodobnie podlega dyrektywie NIS2. Żadnych formularzy, żadnej rejestracji, wynik w 30 sekund.",
        "q1": "Czy Twoja organizacja działa w jednym z sektorów objętych NIS2? Przykłady: energetyka, ochrona zdrowia, transport, infrastruktura cyfrowa lub dostawcy usług ICT.",
        "q1_yes": "Tak / prawdopodobnie tak",
        "q1_no": "Nie / nie jestem pewien",
        "q2": "Jak duża jest Twoja organizacja?",
        "q2_small": "Poniżej 50 osób i poniżej 10 mln EUR obrotu",
        "q2_medium": "50-249 osób lub 10-50 mln EUR obrotu",
        "q2_large": "250 lub więcej osób albo powyżej 50 mln EUR obrotu",
        "v_in": "Twoja organizacja prawdopodobnie podlega NIS2 jako podmiot istotny lub ważny. Dokładna kategoria zależy od konkretnego sektora i rodzaju działalności. Warto zrobić pełne badanie zakresu i skonsultować się z prawnikiem lub sprawdzić wytyczne CERT Polska.",
        "v_small": "Organizacje tej wielkości są generalnie poniżej progu NIS2 i raczej nie są bezpośrednio objęte dyrektywą. Wyjątki istnieją, na przykład gdy jesteś jedynym dostawcą usługi krytycznej w danym regionie. Potwierdź to w pełnym teście zakresu, żeby mieć pewność.",
        "v_out": "Bezpośrednio NIS2 raczej Cię nie dotyczy. Pamiętaj jednak, że jeśli obsługujesz podmioty istotne lub ważne, ich wymagania łańcucha dostaw mogą spływać na Ciebie. Warto sprawdzić to dokładniej w pełnym teście.",
        "cta": "Chcesz wiedzieć, co konkretnie musisz zrobić i ile to kosztuje?",
        "btn_email": "Wyślij mi checklistę NIS2",
        "email_prompt": "Podaj swój adres e-mail, a wyślemy Ci checklistę NIS2 i wstępny plan działania. Możesz zrezygnować z subskrypcji w każdej chwili, jednym kliknięciem.",
        "email_ok": "Gotowe. Sprawdź skrzynkę, wiadomość powinna być już za chwilę. Jeśli nie widzisz, zajrzyj do folderu spam.",
        "email_bad": "Ten adres wygląda nieprawidłowo. Napisz jeszcze raz, w formacie np. jan.kowalski@firma.pl."
      },
      "channel": null
    },
    "cs": {
      "country": "Česká republika",
      "lang": "cs",
      "domain": "nis2-nastroje.cz",
      "subscribe": "https://nis2-nastroje.cz/subscribe",
      "links": [
        {
          "text": "Porovnání nástrojů NIS2",
          "url": "https://nis2-nastroje.cz/srovnani"
        },
        {
          "text": "Kalkulačka nákladů NIS2",
          "url": "https://nis2-nastroje.cz/kalkulacka-nakladu-nis2"
        }
      ],
      "strings": {
        "greeting": "Ahoj. Tento bot vám za dvě otázky řekne, jestli se vás NIS2 pravděpodobně týká. Žádná registrace, žádné kecy.",
        "q1": "Působíte v některém z těchto odvětví: energetika, doprava, zdravotnictví, digitální infrastruktura, výroba kritických produktů, bankovnictví, vodárenství nebo podobné?",
        "q1_yes": "Ano, nebo asi ano",
        "q1_no": "Ne, nebo nevím",
        "q2": "Jak velká je vaše organizace?",
        "q2_small": "Pod 50 lidí a pod 10 mil. EUR",
        "q2_medium": "50-249 lidí nebo 10-50 mil. EUR",
        "q2_large": "250+ lidí nebo přes 50 mil. EUR",
        "v_in": "Vaše organizace pravděpodobně spadá pod NIS2 jako důležitý nebo zásadní subjekt. Přesné zařazení závisí na konkrétním odvětví a roli. Doporučujeme projít si úplný test na webu NÚKIB nebo se poradit s odborníkem.",
        "v_small": "Organizace vaší velikosti jsou zpravidla mimo rozsah NIS2. Výjimkou jsou případy, kdy jste jediným poskytovatelem kritické služby nebo vás NÚKIB výslovně určí. Pro jistotu si ověřte svou situaci přes úplný test.",
        "v_out": "Přímá povinnost z NIS2 se vás pravděpodobně netýká. Pozor ale na dodavatelský řetězec: pokud dodáváte zásadním nebo důležitým subjektům, mohou na vás přenést část svých požadavků. Vyplatí se to prověřit.",
        "cta": "Chcete vědět, co to pro vás konkrétně znamená?",
        "btn_email": "Pošlete mi NIS2 checklist",
        "email_prompt": "Napište svůj e-mail a pošleme vám checklist i přehled prvních kroků. Odhlásit se můžete kdykoli, jedním klikem.",
        "email_ok": "Hotovo. Zkontrolujte svoji schránku, checklist by tam měl být za chvíli.",
        "email_bad": "To nevypadá jako platná e-mailová adresa. Zkuste to prosím znovu, třeba ve formátu jmeno@firma.cz."
      },
      "channel": "https://t.me/nis2nastrojecz"
    },
    "sk": {
      "country": "Slovensko",
      "lang": "sk",
      "domain": "nis2-nastroje.sk",
      "subscribe": "https://nis2-nastroje.sk/subscribe",
      "links": [
        {
          "text": "Porovnanie nástrojov NIS2",
          "url": "https://nis2-nastroje.sk/porovnanie"
        },
        {
          "text": "Kalkulačka nákladov NIS2",
          "url": "https://nis2-nastroje.sk/kalkulacka-nakladov-nis2"
        }
      ],
      "strings": {
        "greeting": "Vitajte. Tento bezplatný test vám za dve otázky povie, či sa na vás pravdepodobne vzťahuje európska smernica NIS2. Nie je to právna porada, ale dobrý prvý orientačný bod.",
        "q1": "Pôsobíte v niektorom z týchto odvetví alebo v oblasti im podobnej? Napríklad: energetika, doprava, zdravotníctvo, digitálna infraštruktúra, bankovníctvo, potravinárstvo alebo výroba kritických produktov.",
        "q1_yes": "Áno, pravdepodobne áno",
        "q1_no": "Nie, neviem posúdiť",
        "q2": "Ako veľká je vaša organizácia?",
        "q2_small": "Pod 50 zamestnancov a pod 10 mil. €",
        "q2_medium": "50 až 249 zamestnancov alebo 10 až 50 mil. €",
        "q2_large": "250+ zamestnancov alebo nad 50 mil. €",
        "v_in": "Vaša organizácia pravdepodobne spadá pod NIS2 ako základná alebo dôležitá entita. Presné zaradenie závisí od konkrétneho pododvetvia. Odporúčame urobiť úplný samotest a v prípade pochybností sa poradiť s NBÚ alebo odborným poradcom.",
        "v_small": "Organizácie vašej veľkosti sú vo všeobecnosti pod hranicou, na ktorú sa NIS2 vzťahuje, a pravdepodobne teda nie ste priamo povinní. Výnimkou je napríklad jediný poskytovateľ kritickej služby alebo prevádzkovateľ DNS, TLD či dôveryhodnostnej služby. Ak si nie ste istí, odporúčame overiť to úplným testom alebo priamo cez NBÚ.",
        "v_out": "Priamo pod NIS2 pravdepodobne nespadáte. Pozor však na dodávateľský reťazec: ak dodávate produkty alebo služby základným či dôležitým entitám, tie na vás môžu prenášať požiadavky zmluvnou cestou. Pre istotu odporúčame prejsť úplným testom.",
        "cta": "Chcete vedieť, čo konkrétne vás čaká a koľko to môže stáť?",
        "btn_email": "Pošlite mi NIS2 kontrolný zoznam",
        "email_prompt": "Napíšte nám svoju e-mailovú adresu a pošleme vám NIS2 kontrolný zoznam aj návrh ďalších krokov. Z odberu sa môžete kedykoľvek odhlásiť.",
        "email_ok": "Ďakujeme. Skontrolujte si doručenú poštu, správa je na ceste.",
        "email_bad": "Táto adresa nevyzerá správne. Skúste prosím znova, napíšte platnú e-mailovú adresu."
      },
      "channel": "https://t.me/nis2nastrojesk"
    },
    "ro": {
      "country": "România",
      "lang": "ro",
      "domain": "nis2-instrumente.ro",
      "subscribe": "https://nis2-instrumente.ro/subscribe",
      "links": [
        {
          "text": "Compară instrumentele NIS2",
          "url": "https://nis2-instrumente.ro/comparatie"
        },
        {
          "text": "Calculator costuri NIS2",
          "url": "https://nis2-instrumente.ro/calculator-costuri-nis2"
        }
      ],
      "strings": {
        "greeting": "Bună. Acest instrument îți spune în două întrebări dacă organizația ta intră probabil sub incidența NIS2. Gratuit, fără date personale.",
        "q1": "Organizația ta activează într-unul din sectoarele acoperite de NIS2? De exemplu: energie, transport, sănătate, infrastructură digitală, servicii bancare sau financiare.",
        "q1_yes": "Da, activăm în astfel de sectoare",
        "q1_no": "Nu sau nu știu sigur",
        "q2": "Câți angajați are organizația și care e cifra de afaceri anuală?",
        "q2_small": "Sub 50 angajați și sub 10M EUR",
        "q2_medium": "50-249 angajați sau 10-50M EUR",
        "q2_large": "250+ angajați sau peste 50M EUR",
        "v_in": "Organizația ta intră cel mai probabil în domeniul de aplicare NIS2, ca entitate esențială sau importantă. Clasificarea exactă depinde de sub-sectorul în care activezi. Recomandăm o verificare completă și, dacă e nevoie, consultarea unui specialist sau a ghidurilor publicate de DNSC.",
        "v_small": "Ca regulă generală, organizațiile mici sunt în afara domeniului de aplicare NIS2. Există totuși excepții: furnizori unici ai unui serviciu critic, furnizori DNS, TLD sau servicii de încredere pot fi incluși indiferent de dimensiune. Merită să confirmi că nu te încadrezi într-una din aceste situații speciale.",
        "v_out": "Cel mai probabil nu ești direct vizat de NIS2. Atenție însă: dacă furnizezi servicii unor entități esențiale sau importante, acestea pot impune cerințe de securitate prin contract. Fă verificarea completă ca să știi exact unde te afli.",
        "cta": "Vrei să mergi mai departe? Compară soluții sau estimează costurile de conformare.",
        "btn_email": "Trimite-mi lista de verificare NIS2",
        "email_prompt": "Răspunde la acest mesaj cu adresa ta de email și îți trimitem lista de verificare NIS2 plus un plan de acțiune pentru organizația ta. Te poți dezabona oricând, dintr-un singur click.",
        "email_ok": "Gata. Verifică-ți inbox-ul în câteva minute. Dacă nu găsești emailul, uită-te și în Spam.",
        "email_bad": "Adresa introdusă nu pare validă. Răspunde cu o adresă de email corectă, de forma exemplu@companie.ro."
      },
      "channel": "https://t.me/nis2instrumente"
    },
    "hu": {
      "country": "Magyarország",
      "lang": "hu",
      "domain": "nis2-eszkozok.hu",
      "subscribe": "https://nis2-eszkozok.hu/subscribe",
      "links": [
        {
          "text": "NIS2 eszközök összehasonlítása",
          "url": "https://nis2-eszkozok.hu/osszehasonlitas"
        },
        {
          "text": "NIS2 költségkalkulátor",
          "url": "https://nis2-eszkozok.hu/nis2-koltsegkalkulator"
        }
      ],
      "strings": {
        "greeting": "Szia! Ez egy ingyenes, 2 kérdéses gyorsellenőrzés: kideríti, hogy szervezeted valószínűleg a NIS2 hatálya alá esik-e. Nem jogi tanácsadás, de jó kiindulópont.",
        "q1": "Milyen területen működik a szervezeted? Az energetika, egészségügy, közlekedés, digitális infrastruktúra és még vagy egy tucat szektor szerepel a NIS2 hatálya alatt.",
        "q1_yes": "Igen, ilyen szektorban vagyunk",
        "q1_no": "Nem, vagy nem tudom",
        "q2": "Mekkora a szervezeted mérete?",
        "q2_small": "Kis cég: 50 fő alatt és 10M EUR alatt",
        "q2_medium": "Közepes: 50-249 fő, vagy 10-50M EUR",
        "q2_large": "Nagy: 250+ fő, vagy 50M EUR felett",
        "v_in": "Szervezeted valószínűleg a NIS2 hatálya alá esik, lényeges vagy fontos szervezetként. A pontos besorolás az érintett részágazattól függ. Érdemes az SZTFH teljes önértékelő eszközével is elvégezni az ellenőrzést, hogy biztos legyél.",
        "v_small": "A méretküszöb alapján szervezeted valószínűleg nem esik közvetlenül a NIS2 hatálya alá. Kivétel lehet, ha például egyedüli szolgáltatója vagy egy kritikus funkciónak, vagy ha az SZTFH külön kijelöl. Ezt érdemes egyszer alaposabban is körbejárni.",
        "v_out": "Közvetlenül valószínűleg nem érint a NIS2, de figyelj arra: ha lényeges vagy fontos szervezeteknek szállítasz be, ők megkövetelhetik tőled is a megfelelő biztonsági szintet. Egy részletesebb átvilágítás itt sem árt.",
        "cta": "Nézd meg, mi vár rád pontosan, és mit érdemes lépni.",
        "btn_email": "Küldjétek el a NIS2 ellenőrző listát",
        "email_prompt": "Add meg az e-mail-címedet, és elküldjük a NIS2 ellenőrző listát és a javasolt következő lépéseket. Bármikor leiratkozhatsz, egy kattintással.",
        "email_ok": "Megkaptuk, köszönjük! Nézd meg a beérkező leveleidet, hamarosan megérkezik az anyag.",
        "email_bad": "Ez nem tűnik érvényes e-mail-címnek. Kérlek, adj meg egy helyes e-mail-címet, és így tudjuk elküldeni az anyagot."
      },
      "channel": "https://t.me/nis2eszkozok"
    },
    "it": {
      "country": "Italia",
      "lang": "it",
      "domain": "nis2-strumenti.it",
      "subscribe": "https://nis2-strumenti.it/subscribe",
      "links": [
        {
          "text": "Confronta gli strumenti NIS2",
          "url": "https://nis2-strumenti.it/confronto"
        },
        {
          "text": "Calcolatore costi NIS2",
          "url": "https://nis2-strumenti.it/calcolatore-costi-nis2"
        }
      ],
      "strings": {
        "greeting": "Ciao. Questo è un controllo rapido in 2 domande per capire se la tua organizzazione rientra nell'ambito della direttiva NIS2. È gratuito e non sostituisce una verifica legale.",
        "q1": "La tua organizzazione opera in uno di questi settori: energia, trasporti, sanità, infrastrutture digitali? O in altri settori critici coperti dalla NIS2?",
        "q1_yes": "Sì, probabilmente sì",
        "q1_no": "No / non sono sicuro",
        "q2": "Quanti dipendenti ha la tua organizzazione e qual è il fatturato annuo?",
        "q2_small": "Sotto 50 dipendenti e sotto 10M €",
        "q2_medium": "50-249 dipendenti, oppure 10-50M €",
        "q2_large": "250+ dipendenti, oppure oltre 50M €",
        "v_in": "La tua organizzazione rientra probabilmente nell'ambito NIS2 come soggetto essenziale o importante. La classificazione esatta dipende dal sotto-settore specifico in cui operi. Ti consigliamo di completare la verifica completa e, se necessario, di confrontarti con un consulente o con le indicazioni dell'ACN.",
        "v_small": "In base alle dimensioni dichiarate, la tua organizzazione è probabilmente al di sotto delle soglie previste dalla NIS2 e non rientra nell'ambito di applicazione. Fanno eccezione i casi in cui sei l'unico fornitore di un servizio critico o rientri in categorie specificamente designate. Meglio confermare con una verifica più approfondita.",
        "v_out": "La tua organizzazione probabilmente non è soggetta direttamente alla NIS2. Attenzione però: se fornisci servizi a soggetti essenziali o importanti, potresti essere coinvolto indirettamente attraverso i requisiti della catena di fornitura. Vale la pena fare un controllo più completo per escluderlo con certezza.",
        "cta": "Vuoi capire cosa cambia in concreto per te e quanto potrebbe costare adeguarsi?",
        "btn_email": "Inviami la checklist NIS2",
        "email_prompt": "Rispondimi con la tua email e ti mando la checklist NIS2 e un piano d'azione concreto. Puoi cancellarti quando vuoi, senza complicazioni.",
        "email_ok": "Perfetto. Controlla la tua casella di posta: troverai la checklist e le prossime indicazioni a breve.",
        "email_bad": "L'indirizzo non sembra valido. Rispondimi con un'email corretta e ti mando subito i materiali."
      },
      "channel": "https://t.me/nis2strumenti"
    }
  }
};

const EMAIL_RE = /^[^\s@]+@[^\s@]+\.[^\s@]+$/;

async function tg(token, method, body) {
  return fetch(`https://api.telegram.org/bot${token}/${method}`, {
    method: "POST",
    headers: { "Content-Type": "application/json" },
    body: JSON.stringify(body),
  });
}

function market(mk) {
  return CONFIG.markets[mk] || null;
}

function chooser() {
  const rows = Object.keys(CONFIG.markets).map((mk) => [
    { text: CONFIG.markets[mk].country, callback_data: `st:${mk}` },
  ]);
  return { inline_keyboard: rows };
}

function q1kb(s, mk) {
  return { inline_keyboard: [
    [{ text: s.q1_yes, callback_data: `q1:Y:${mk}` }],
    [{ text: s.q1_no, callback_data: `q1:N:${mk}` }],
  ] };
}

function q2kb(s, sec, mk) {
  return { inline_keyboard: [
    [{ text: s.q2_small, callback_data: `q2:${sec}:S:${mk}` }],
    [{ text: s.q2_medium, callback_data: `q2:${sec}:M:${mk}` }],
    [{ text: s.q2_large, callback_data: `q2:${sec}:L:${mk}` }],
  ] };
}

// sector (Y/N) + size (S/M/L) -> { text, score }
function verdict(s, sec, size) {
  if (sec === "N") return { text: s.v_out, score: 6 };
  if (size === "S") return { text: s.v_small, score: 4 };
  return { text: s.v_in, score: 2 };
}

function ctaKb(m, score, mk) {
  const rows = (m.links || []).slice(0, 2).map((l) => [{ text: l.text, url: l.url }]);
  rows.push([{ text: m.strings.btn_email, callback_data: `em:${score}:${mk}` }]);
  return { inline_keyboard: rows };
}

async function start(token, chatId, mk) {
  const m = market(mk);
  if (!m) return tg(token, "sendMessage", { chat_id: chatId, text: "🌍 Select your country:", reply_markup: chooser() });
  const s = m.strings;
  return tg(token, "sendMessage", {
    chat_id: chatId, text: `${s.greeting}\n\n${s.q1}`, reply_markup: q1kb(s, mk),
  });
}

async function handleCallback(token, cq) {
  const data = cq.data || "";
  const chatId = cq.message && cq.message.chat && cq.message.chat.id;
  const msgId = cq.message && cq.message.message_id;
  // always stop the button spinner
  await tg(token, "answerCallbackQuery", { callback_query_id: cq.id });
  const parts = data.split(":");
  const kind = parts[0];

  if (kind === "st") {                       // chooser -> start a market
    return start(token, chatId, parts[1]);
  }
  if (kind === "q1") {                        // sector answered -> ask size
    const sec = parts[1], mk = parts[2];
    const m = market(mk); if (!m) return;
    return tg(token, "editMessageText", {
      chat_id: chatId, message_id: msgId, text: m.strings.q2, reply_markup: q2kb(m.strings, sec, mk),
    });
  }
  if (kind === "q2") {                        // size answered -> verdict + CTA
    const sec = parts[1], size = parts[2], mk = parts[3];
    const m = market(mk); if (!m) return;
    const v = verdict(m.strings, sec, size);
    return tg(token, "editMessageText", {
      chat_id: chatId, message_id: msgId,
      text: `${v.text}\n\n${m.strings.cta}`, reply_markup: ctaKb(m, v.score, mk),
      disable_web_page_preview: true,
    });
  }
  if (kind === "em") {                        // email button -> force-reply prompt
    const score = parts[1], mk = parts[2];
    const m = market(mk); if (!m) return;
    // market+score recovered later from this prompt's text (reply_to_message)
    return tg(token, "sendMessage", {
      chat_id: chatId,
      text: `${m.strings.email_prompt}\n\n[ref:${mk}:${score}]`,
      reply_markup: { force_reply: true },
    });
  }
}

async function captureLead(token, msg, mk, score) {
  const m = market(mk);
  const email = (msg.text || "").trim().toLowerCase();
  if (!m) return;
  if (!EMAIL_RE.test(email)) {
    return tg(token, "sendMessage", { chat_id: msg.chat.id, text: m.strings.email_bad,
      reply_markup: { force_reply: true } });
  }
  // forward to that market's own /subscribe (fires beehiiv + Resend nurture)
  try {
    await fetch(m.subscribe, {
      method: "POST", headers: { "Content-Type": "application/json" },
      body: JSON.stringify({ email, source: "telegram-bot", quiz_answers: { score: Number(score) || 0 } }),
    });
  } catch (e) { /* fail-open: still confirm to the user */ }
  return tg(token, "sendMessage", { chat_id: msg.chat.id, text: m.strings.email_ok });
}

async function handleMessage(token, msg) {
  const text = (msg.text || "").trim();
  // email reply to our prompt?
  const replyText = msg.reply_to_message && msg.reply_to_message.text;
  if (replyText) {
    const ref = replyText.match(/\[ref:([a-z]{2}):(\d)\]/);
    if (ref) return captureLead(token, msg, ref[1], ref[2]);
  }
  if (text.startsWith("/start")) {
    const payload = text.split(/\s+/)[1] || "";
    return start(token, msg.chat.id, payload.toLowerCase());
  }
  // any other message -> nudge to start
  return start(token, msg.chat.id, "");
}

export async function onRequestPost({ request, env }) {
  const token = env.TELEGRAM_BOT_TOKEN;
  if (!token) return new Response("not configured", { status: 200 });
  if (env.TG_WEBHOOK_SECRET) {
    const got = request.headers.get("X-Telegram-Bot-Api-Secret-Token");
    if (got !== env.TG_WEBHOOK_SECRET) return new Response("forbidden", { status: 403 });
  }
  let update;
  try { update = await request.json(); } catch { return new Response("ok", { status: 200 }); }
  try {
    if (update.callback_query) await handleCallback(token, update.callback_query);
    else if (update.message) await handleMessage(token, update.message);
  } catch (e) { /* never 500 back to Telegram, it would retry forever */ }
  return new Response("ok", { status: 200 });
}

export async function onRequestGet() {
  return new Response("NIS2 scope-check bot webhook is live.", { status: 200 });
}
