// generated by tools/affiliate_router.py — edit db/affiliate-links.json then `sync`
// /go/<vendor>: approved -> affiliate URL + per-site SubID; pending -> vendor site; unknown -> home.
// Every hit is also logged server-side to GA4 (event go_click, params vendor/site/monetized)
// so the weekly money digest can count clicks without relying on vendor dashboards.
const SITE = "nis2-strumenti-it";
const MAP = {
  "nordlayer": {
    "url": "",
    "direct": "https://nordlayer.com/",
    "subid_param": "subid"
  },
  "1password": {
    "url": "",
    "direct": "https://1password.com/",
    "subid_param": "sid"
  },
  "bitwarden": {
    "url": "",
    "direct": "https://bitwarden.com/",
    "subid_param": "subid"
  },
  "bitdefender": {
    "url": "",
    "direct": "https://bitdefender.com/",
    "subid_param": "sid"
  },
  "acronis": {
    "url": "https://www.tkqlhce.com/click-101804169-13492976",
    "direct": "https://acronis.com/",
    "subid_param": "sid"
  },
  "sprinto": {
    "url": "",
    "direct": "https://sprinto.com/",
    "subid_param": "subid"
  },
  "reglyze": {
    "url": "https://reglyze.com/",
    "direct": "https://reglyze.com/",
    "subid_param": "via"
  },
  "secfix": {
    "url": "",
    "direct": "https://secfix.com/",
    "subid_param": "subid"
  },
  "isms": {
    "url": "",
    "direct": "https://isms.online/",
    "subid_param": "subid"
  },
  "vanta": {
    "url": "",
    "direct": "https://vanta.com/",
    "subid_param": "subid"
  },
  "complycloud": {
    "url": "",
    "direct": "https://complycloud.eu/",
    "subid_param": "subid"
  },
  "drata": {
    "url": "",
    "direct": "https://drata.com/",
    "subid_param": "subid"
  },
  "userway": {
    "url": "",
    "direct": "https://userway.org/",
    "subid_param": "subid"
  },
  "equalweb": {
    "url": "https://www.equalweb.com/#a_aid=080889&a_bid=11110002",
    "direct": "https://equalweb.com/",
    "subid_param": "subid"
  },
  "equalizedigital": {
    "url": "https://equalizedigital.com/accessibility-checker/?ref=partnerships@nis2-narzedzia.pl",
    "direct": "https://equalizedigital.com/",
    "subid_param": "subid"
  },
  "secureframe": {
    "url": "",
    "direct": "https://secureframe.com/",
    "subid_param": "gsxid"
  }
};
const GA = {"mid": "G-GME940XQ5N", "secret": "gPgQD5bmRoSa1bAL70CR2A"};

export async function onRequestGet(context) {
  const { params, request } = context;
  const vendor = String(params.vendor || "").toLowerCase().replace(/[^a-z0-9_-]/g, "");
  const url = new URL(request.url);
  const entry = MAP[vendor] || null;
  let dest;
  if (entry && entry.url) dest = withSubId(entry.url, entry.subid_param || "subid", SITE);
  else if (entry && entry.direct) dest = entry.direct;
  else dest = url.origin;
  if (GA && GA.mid && GA.secret && typeof context.waitUntil === "function") {
    context.waitUntil(logClick(request, vendor, !!(entry && entry.url)));
  }
  return Response.redirect(dest, 302);
}

function logClick(request, vendor, monetized) {
  const ref = request.headers.get("referer") || "";
  const cid = Math.floor(Math.random() * 1e10) + "." + Math.floor(Date.now() / 1000);
  const body = JSON.stringify({
    client_id: cid,
    events: [{ name: "go_click", params: {
      vendor: vendor || "(unknown)", site: SITE, monetized: monetized ? "yes" : "no",
      page_referrer: ref.slice(0, 400), engagement_time_msec: 1,
    }}],
  });
  return fetch("https://www.google-analytics.com/mp/collect?measurement_id=" + GA.mid +
               "&api_secret=" + GA.secret, { method: "POST", body }).catch(function () {});
}

function withSubId(base, param, site) {
  try { const d = new URL(base); if (!d.searchParams.has(param)) d.searchParams.set(param, site); return d.toString(); }
  catch (_) { return base; }
}
